# Generated by Django 5.1.1 on 2024-10-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
