# Generated by Django 5.1.1 on 2024-10-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzhub', '0002_solution_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='delete',
            new_name='deleted',
        ),
    ]
