# Generated by Django 5.1.1 on 2024-10-10 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzhub', '0003_rename_delete_solution_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='quizzhub.quiz'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizzhub.solution'),
        ),
    ]
